name: sts
channels:
    - conda-forge
    - fastai
    - pytorch
    - defaults
dependencies:
  - git
  - python
  - numpy
  - pandas
  - plotly
  - fastbook
  - fastai
  - pytorch
  - torchvision
  - dtreeviz
  - sentencepiece